## Data Normalization: Mean Normalization

In [1]:
import pandas as pd

data = pd.read_csv("...") # File Path

In [2]:
data.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [3]:
data = data.drop(['Engine Fuel Type', 'Engine Cylinders', 'Driven_Wheels', 'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style'], axis=1)

data.head(10)

,Make,Model,Year,Engine HP,Transmission Type,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,335.0,MANUAL,26,19,3916,46135
1,BMW,1 Series,2011,300.0,MANUAL,28,19,3916,40650
2,BMW,1 Series,2011,300.0,MANUAL,28,20,3916,36350
3,BMW,1 Series,2011,230.0,MANUAL,28,18,3916,29450
4,BMW,1 Series,2011,230.0,MANUAL,28,18,3916,34500
5,BMW,1 Series,2012,230.0,MANUAL,28,18,3916,31200
6,BMW,1 Series,2012,300.0,MANUAL,26,17,3916,44100
7,BMW,1 Series,2012,300.0,MANUAL,28,20,3916,39300
8,BMW,1 Series,2012,230.0,MANUAL,28,18,3916,36900
9,BMW,1 Series,2013,230.0,MANUAL,27,18,3916,37200

**1. Mean Normalization**

In [6]:
cols = ['Engine HP', 'highway MPG', 'city mpg', 'MSRP']

mean_scaled = (data[cols] - data[cols].mean()) / (data[cols].max() - data[cols].min())

mean_scaled_df = mean_scaled.add_suffix('_scaled')

comparasion_mean = pd.concat([data[cols], mean_scaled_df], axis=1)
comparasion_mean.head(11)

,Engine HP,highway MPG,city mpg,MSRP,Engine HP_scaled,highway MPG_scaled,city mpg_scaled,MSRP_scaled
0,335.0,26,19,46135,0.090501,-0.001864,-0.005640,0.002684
1,300.0,28,19,40650,0.053503,0.003984,-0.005640,0.000027
2,300.0,28,20,36350,0.053503,0.003984,0.002052,-0.002057
3,230.0,28,18,29450,-0.020493,0.003984,-0.013333,-0.005400
4,230.0,28,18,34500,-0.020493,0.003984,-0.013333,-0.002953
5,230.0,28,18,31200,-0.020493,0.003984,-0.013333,-0.004552
6,300.0,26,17,44100,0.053503,-0.001864,-0.021025,0.001698
7,300.0,28,20,39300,0.053503,0.003984,0.002052,-0.000627
8,230.0,28,18,36900,-0.020493,0.003984,-0.013333,-0.001790
9,230.0,27,18,37200,-0.020493,0.001060,-0.013333,-0.001645
10,300.0,28,20,39600,0.053503,0.003984,0.002052,-0.000482

**2. Comparasion**

In [8]:
comparison = pd.DataFrame({
    'Kolom': cols,
    'Min (Original)': data[cols].min().values,
    'Max (Original)': data[cols].max().values,
    'Min (Mean Norm)': mean_scaled_df.min().values,
    'Max (Mean Norm)': mean_scaled_df.max().values,
    })

comparison

,Kolom,Min (Original),Max (Original),Min (Mean Norm),Max (Mean Norm)
0,Engine HP,55.0,1001.0,-0.205482,0.794518
1,highway MPG,12.0,354.0,-0.042800,0.957200
2,city mpg,7.0,137.0,-0.097948,0.902052
3,MSRP,2000.0,2065902.0,-0.018700,0.981300